### PR TITLE
Add support for new absence operator (#33)

### PR DESCRIPTION
**Pull request by janosch-x**

### CODE REVIEW

**Comment by ammar** [comment]
Hi @janosch-x . Thanks for this and sorry about the delayed response.

My initial thinking was this new "operator" is not really a "group" and thus had started investigating an alternative approach. However the fact that the new construct allows for any sub-expression to appear as a `exp` makes using the group approach easier because it will use the existing scanner recursion. for example in a case like `(?~abc|def|[ghi])`

So, this is probably the best approach now and it looks good.

Cheers and thanks again!

**Comment by ammar** [comment]
@janosch-x 

On further review I noticed a couple of things:

- Need to double check the addition of `Absent` to `Group::All` based on where it is used (see ruby 1.8.6 syntax file)
- The new type/token (`:group`/`:absent`) should be added to the ruby 2.4.1 syntax file with a call to `implements`.

**Comment by janosch-x** [comment]
Hi @ammar,

thanks for the feedback.

I also pondered whether it really is a group, ending up with the same conclusion as you did. To be sure I even asked the author, and [he does see it is a group]( https://github.com/k-takata/Onigmo/issues/87#issuecomment-291506000 ) :)

> Need to double check the addition of Absent to Group::All based on where it is used (see ruby 1.8.6 syntax file)

This is indeed a mistake. Do you have a preferred solution? I think `All` should contain `Absent`, because it doesn't seem right to handle version differences in `Token::Group`. Maybe we could write `Group::All - [Group::Absent]` in the 1.8.6 syntax file? Of course that is not very pretty either ...

**Comment by janosch-x** [comment]
Or maybe remove `Group::All` and list all the "classical" group types individually in the 1.8.6 file?

**Comment by janosch-x** [comment]
@ammar In accordance with other token files I've removed the new type constant from the `All` array and called `implement` on it separately in the 2.4.1 file.

There is also a syntax file test and a parser test for it now.

Lastly, to match the naming in Onigmo, I have changed the name from "absent" to "absence".

**Comment by ammar** [comment]
@janosch-x Sorry for not responding sooner. I recently had an accident and have an arm and a shoulder in cast. Hope to be able to work again soon

**Comment by janosch-x** [comment]
@ammar I'm sorry to hear that. Please don't feel pressurised by my landslide of PRs. There is no urgency there at all, I had just been bored. Wishing you a good recovery!

**Comment by ammar** [comment]
Hi @janosch-x, thanks for looking into the classification of the operator and the updates. Again, I'm very sorry for the very late response.

I think this looks good and I would like to merge it.

Cheers!

**Comment by ammar** [comment]
Included in release 0.4.4

**Pull request merged**
