### PR TITLE
Add support for Ruby 2.3.4 version

### PR DESCRIPTION
**Pull request by barthez**
- Adds ruby version files file for ruby 2.3.4

/cc @ammar 

Would you mind to release a new version with this fix? I'm working on https://github.com/mbj/mutant/pull/719 and I cannot run CI on Ruby 2.3.4 without this change.

### CODE REVIEW

**Comment by ammar** [comment]
@barthez, Thanks for this. I've been recovering from an accident and just took off my casts and started to catch up with work. I hope to get some time to review this by the coming weekend, at the latest.

**Comment by barthez** [comment]
No need to rush. I've found a way to run CI on 2.3.3 on `mutant` repo.

Get well!

**Comment by ammar** [comment]
Included in release 0.4.4

**Comment by mbj** [comment]
@barthez Will you do a dependency bump for mutant, or should I take up the stab?

**Comment by barthez** [comment]
@mbj https://github.com/mbj/mutant/pull/722

**Pull request merged**
