### PR TITLE
Automatically support new rubies, specify only versions with changes

### PR DESCRIPTION
**Pull request by janosch-x**
#52

### CODE REVIEW

**Comment by ammar** [comment]
This looks better than I imagined it would :)

I was a little confused at first then I realized that I had missed a recent change [(@d02cb01)](https://github.com/ammar/regexp_parser/commit/d02cb019a682a962d8de5ab5c2644938e852e68a) that set the `VERSIONS` array directly from the the files.

I also seriously doubt anyone is using `Regexp::Syntax::VERSIONS` or `Regexp::Syntax::Ruby.constants`. Even if there were any, the minor version bump that this change warrants should communicate that.

Is the remaining failing test a reminder for something? I assume it's supposed to be?:

```ruby
  def test_syntax_file_2_5_alias
    syntax = Regexp::Syntax.new 'ruby/2.5'

    assert syntax.kind_of?(Regexp::Syntax::Ruby::V25)
  end
```

Thanks!

**Comment by janosch-x** [comment]
It seems to fail only on ruby-head so I'll have to look into that. There is also some spaghettiness that I want to remove, and one or two things to make a little more object-oriented. 

Perhaps a larger refactoring could lead to an even better solution. E.g. the Syntax versions could be modules instead of the current classes with their deep inheritance tree. That way, any subset - such as all versions up to a number -  could be used to build up a Syntax object using #extend. This could yield a less "magic" solution and one with less logic than what I've built here. But that could also be something for later.

**Comment by bobziuchkovski** [comment]
Thanks a lot for taking a look into this.  Automatically-supported patch revisions would be a huge boon to us!

**Comment by bobziuchkovski** [comment]
Not sure if the breaking change will be a blocker or not, but if it helps at all, I looked through a [search of Github projects referring to Regexp::Syntax::Versions](https://github.com/search?utf8=%E2%9C%93&q=%22Regexp%3A%3ASyntax%3A%3AVERSIONS%22&type=Code) and the only results were vendored copies of this gem itself.

I also looked at a [more general search of references to Regexp::Syntax](https://github.com/search?l=Ruby&p=1&q="Regexp%3A%3ASyntax"&type=Code).  I paged through all 77 result pages and saw only a single result that a) wasn't a vendored copy of this gem, and b) was actually referring to anything under Regexp::Syntax for this gem.  [That result](https://github.com/gjtorikian/ecma-re-validator/blob/787a73909c8394324ca25dbb08a4738210ab7cce/lib/ecma-re-validator.rb#L11) just refers to `Regexp::Syntax::Token::UnicodeProperty::All`, which wouldn't be affected.

There could be closed source projects or projects hosted outside of Github that could break, but at the very least it looks like very few projects poke at the internals of `regexp_parser`.

**Comment by ammar** [comment]
Sorry for the delayed response. Busy week at work. I will have time to review this weekend. Thanks @janosch-x!

**Comment by ammar** [comment]
Nice. That looks so much cleaner.

Now that the gem doesn't fail on new ruby versions, what do you think about adding a warning if the requested version is not a known?

None of these are really, well, realistic
```ruby
Regexp::Parser.parse(/foo/, 'ruby/9.9.99')
Regexp::Parser.parse(/foo/, 'ruby/9.99.9')
Regexp::Parser.parse(/foo/, 'ruby/99.9.9')
```

But they fail with a strange error:
```
NameError (uninitialized constant Regexp::Syntax::V9_9_99)
Did you mean?  Regexp::Syntax::V9_9_9
```

Not sure why that suggestion is being made by did_you_mean, but that's another story.

This looks great. Thanks

**Pull request merged**
