### PR TITLE
Fix quantifier text for modified intervals

### LINKED ISSUE #16: Incorrect `#to_s` output for reluctant interval
```ruby
2.3.0 :504 > regex = /a{3}?/
 => /a{3}?/
2.3.0 :505 > Regexp::Parser.parse(regex).to_re == regex
 => false
2.3.0 :506 > Regexp::Parser.parse(regex).to_re
 => /a{3}/
```

It looks like the issue is the quantifier being set with incorrect text:

```ruby
2.3.0 :508 > Regexp::Parser.parse(regex).first
 => #<Regexp::Expression::Literal:0x007fedbbdc4398 @type=:literal, @token=:literal, @text="a", @ts=0, @level=0, @set_level=0, @conditional_level=0, @options=nil, @quantifier=#<Regexp::Expression::Quantifier:0x007fedbbdc4118 @token=:interval, @text="{3}", @mode=:reluctant, @min=3, @max=3>>
2.3.0 :509 > Regexp::Parser.parse(regex).first.quantifier
 => #<Regexp::Expression::Quantifier:0x007fedbbd75608 @token=:interval, @text="{3}", @mode=:reluctant, @min=3, @max=3>
2.3.0 :510 > Regexp::Parser.parse(regex).first.quantifier.text
 => "{3}"
```

### PR DESCRIPTION
**Pull request by backus**
Fixes text for reluctant and possessive interval quantifiers

Fixes #16

### CODE REVIEW

**Comment by ammar** [comment]
You're on a roll sir. Thank you. This looks good.

Cheers!

**Comment by ammar** [comment]
@backus, FYI, I just released version 0.3.3. It includes your fixes from #12, #14, and this PR.

Thank you for all these improvements.

**Comment by mbj** [comment]
@ammar Also thx from my side on fast merges / releases. @backus Thx as usual ;)

**Comment by backus** [comment]
> @backus, FYI, I just released version 0.3.3. It includes your fixes from #12, #14, and this PR.
>
> Thank you for all these improvements.

Happy to help! Thanks for being so quick to respond on all the issues and PRs I filled

**Pull request merged**
