### PR TITLE
Allow options to be passed when processing a String pattern

### PR DESCRIPTION
**Pull request by owst**
@jaynetics as mentioned in https://github.com/rubocop-hq/rubocop/pull/8625#issuecomment-691471124 - please let me know what you think 👍

### CODE REVIEW

**Comment by jaynetics** [comment]
@owst thank you, this looks nice!

the only thing we might want to change is how the passed options are silently ignored when used alongside a `Regexp`. this seems a little counterintuitive. i'd either let it raise an error, or we can simply override the options from the `Regexp` if people do try to pass their own options.

@ammar this code uses kwargs, which would mean dropping support for running on 1.9. are you fine with that?

**Comment by owst** [comment]
@jaynetics yeah, good point; I think raising is best (for now)

**Comment by owst** [comment]
Hi @jaynetics just checking-in on this, do you have any further thoughts? I'd love to get this merged and for a new version of `regexp_parser` to be released so I can progress https://github.com/rubocop-hq/rubocop/pull/8625

Thanks!

**Comment by jaynetics** [comment]
@ammar FYI

i have merged this PR which ends support for Ruby 1.9.x and will update the README accordingly. 

i could not find any dependents which seem to require it.

if it turns out you or anyone else really still need such support i suggest we release another version to restore it.

**Comment by jaynetics** [comment]
@owst released with v1.8.0, thanks again!

**Pull request merged**
